name: Update WakaTime Data

on:
  schedule:
    - cron: '0 0 */14 * *'  
  workflow_dispatch:      

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' 

    - name: Install and run wakatime-to-json
      env:
        WAKATIME_USER: ${{ secrets.WAKATIME_USER }}
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      run: |
        npm install wakatime-to-json
        npx wakatime-to-json -o ./wakatime-data.json


    - name: Commit and push changes
      run: |
        git config user.name "GitHub Action"
        git config user.email "github-action@users.noreply.github.com"
        git remote set-url origin https://${{ secrets.GH_TOKEN }}@github.com/3ntr0pia/3ntr0pia.git
        git add wakatime-data.json
        git commit -m "Update WakaTime data"
        git push


