name: Update WakaTime Data

on:
  schedule:
    - cron: '0 0 */14 * *'  # Ejecuta esta acción cada 14 días
  workflow_dispatch:      # Allows manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Updated to Node.js version 16

    - name: Install and run wakatime-to-json
      run: |
        npm install wakatime-to-json
        npx wakatime-to-json -o ./wakatime-data.json

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Action"
        git config user.email "github-action@users.noreply.github.com"
        git add wakatime-data.json
        git commit -m "Update WakaTime data"
        git push
