name: Update WakaTime Data and Generate Chart

on:
  schedule:
    - cron: '0 0 */14 * *'  
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Ensure json_data directory exists
      run: mkdir -p json_data

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' 

    - name: Install and run wakatime-to-json
      env:
        WAKATIME_USER: ${{ secrets.WAKATIME_USER }}
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      run: |
        npm install wakatime-to-json
        npx wakatime-to-json -o ./json_data/$(date +"%Y-%m-%d").json

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib


    - name: Run script to generate chart
      run: |
        python3 generate_chart.py
    - name: List files in current directory
      run: 
        ls -la
    - name: Generate png
      run: |
        git add chart.png
    - name: Update README.md with the latest chart link
      run: |
        echo "![WakaTime languages chart](chart.png)" > README.md

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Action"
        git config user.email "github-action@users.noreply.github.com"
        git remote set-url origin https://${{ secrets.GH_TOKEN }}@github.com/3ntr0pia/3ntr0pia.git
        git add chart.png json_data/*.json README.md
        git commit -m "Update WakaTime data, generate chart, and save accumulated data"
        git push
